version: '3'
services:
  app:
    build:
      context: ./BIGAPP_FAST_APP
    #command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - BIGAPP_FAST_APP/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    # environment:
    #   - DATABASE_URL=postgresql://username:password@postgres:5432/dbname

# React frontend
  react:
    build:
      context: ./bigapp_front
    ports:
      - "3000:3000"
    depends_on:
      - app
    environment:
      - REACT_APP_API_URL=http://app:80

  # PostgreSQL database

  db:
    image: postgres:16-alpine
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    env_file:
      - BIGAPP_FAST_APP/.env
    ports:
      - 5432:5432